//go:build ignore
// +build ignore

// generator.go - Run via 'go run internal/bloomgenerator/bloomgenerator.go' to generate filters.go

package main

import (
	"bytes"
	"encoding/gob"
	"fmt"
	"os"
	"text/template"

	bloom "github.com/bits-and-blooms/bloom/v3"
)

// FIXME: this code is copy pasta from a Google search / AI Mode session, with minor
// changes. It needs a thorough rework to ensure that it works as expected.

func main() {
	// TODO: See if we actually need all of the streets of if we
	// can get away with just encoding the challenging ones: the ones
	// that start with directionals, those that are numeric or
	// alphabetic and might need to be spelled out or not, etc.
	// NOTE: the current generated template file is 100MB without any
	// data in the bloom filter - just zeros. We also have not accounted
	// for the city, region, zip lookup. We'll need to do better than that.

	// Initialize Bloom Filters
	// Estimates for US: ~30M unique combinations. FPR: 0.1% (0.001)
	streetFilter := bloom.NewWithEstimates(30000000, 0.001)

	// Data Ingestion Loop
	// loop through the parsed US Census Bureau TIGER files here
	zipStreetData := []struct {
		Zip    string
		Street string
	}{
		// {"84095", "SOUTH JORDAN"},
		// {"84103", "E"},
	}

	for _, record := range zipStreetData {
		// Generate the lookup key
		key := fmt.Sprintf("%s:%s", record.Zip, record.Street)
		streetFilter.Add([]byte(key))
	}

	// Serialize the Bloom Filter into raw bytes
	var buf bytes.Buffer
	encoder := gob.NewEncoder(&buf)
	if err := encoder.Encode(streetFilter); err != nil {
		panic(err)
	}

	// Generate the Go File containing the embedded asset
	tmpl := `// Code generated by generator.go; DO NOT EDIT.
package compiled_filter

import (
	"bytes"
	"encoding/gob"
	bloom "github.com/bits-and-blooms/bloom/v3"
)

// LoadStreetFilter restores the compiled filter in memory
func LoadStreetFilter() (*bloom.BloomFilter, error) {
	var filter bloom.BloomFilter
	buf := bytes.NewBuffer(RawStreetFilterBytes)
	decoder := gob.NewDecoder(buf)
	if err := decoder.Decode(&filter); err != nil {
		return nil, err
	}
	return &filter, nil
}

// RawStreetFilterBytes holds the pre-compiled Bloom filter
var RawStreetFilterBytes = []byte({
	{{range .Bytes}}{{.}},{{end}}
})

`

	t := template.Must(template.New("filter").Parse(tmpl))

	err := os.MkdirAll("./generated/compiled_filter", 0755)
	if err != nil {
		panic(err)
	}
	outFile, err := os.Create("./generated/compiled_filter/compiled_filters.go")
	if err != nil {
		panic(err)
	}
	defer outFile.Close()

	// Pass the byte slice to the template
	err = t.Execute(outFile, map[string]interface{}{
		"Bytes": buf.Bytes(),
	})
	if err != nil {
		panic(err)
	}
	fmt.Printf("Successfully generated %s\n", outFile.Name())
}
